### PR TITLE
Fix fragaria doc

### PR DESCRIPTION
**Pull request by balthisar**
Not sure when it broke; I guess neither of us runs it regularly. Works again now, though.

### CODE REVIEW

**Comment by shysaur** [comment]
>  I guess neither of us runs it regularly

Yeah, spot-on. I used to, but I stopped for some reason.

Anyway, talking about examples breakage, the preferences of MGSFragariaView (non modern) are broken since 4235b67, but I'm thinking of removing that example in favor of MGSFragariaViewModern, now that the same syntax coloring is enforced for both views and I can restore the split-screen configuration.

**Comment by balthisar** [comment]
That broke when I had to change useStandardPreferences to NO in FragariaView. Given it was in the initializer, I had little choice. I think it's the right thing, though.

**Comment by shysaur** [comment]
> Given it was in the initializer, I had little choice. I think it's the right thing, though.

I thought the same thing when I saw your PR; it's just that keeping around a broken example defies the purpose of having the example in the first place. I didn't ask immediately because I didn't know if you planned to fix it later or not.

(btw, the fix is easy: just add a method to MGSFragariaView which attaches the properties observer to it just like MGSFragaria does in its initializer. I'm not saying you have to implement it though!)

**Comment by shysaur** [comment]
Or, you can remove the preferences from the MGSFragariaView example entirely, to keep it as a playground for testing new features which should not be controllable from user defaults.

**Pull request merged**
