### PR TITLE
Fix for message forwarding doesn't work with KVC. Test Case for Fix.

### PR DESCRIPTION
**Pull request by balthisar**
This was ugly, unexpected behavior, but this seems to patch it up.

It bothers me, though, we now have to maintain separate lists of which properties belong to which object. I feel like I'm nearly re-introducing the docSpec and the old objectForKey: dependencies.

There's a more dynamic way with class_copyPropertyList and property_getAttributes, the latter of which indicates if a method is forwarded or not, but it adds a considerable amount of complexity for something that should be relatively simply. I'm using these on the new Properties Coordinator (defaults) system, so if I end up happy it and bring in the utility code, I might come back to these and do it dynamically instead of with the NSSets.

### CODE REVIEW

**Comment by shysaur** [comment]
For the text view properties, a key path like `textView.string` should work (just use `-valueForKeyPath:` instead of `-valueForKey:`)

If it works for you, I think we can expose without much hassle `SMLSyntaxColouring`, since the API is now fairly clean; then you can use a key path like `textView.syntaxColouring.colourForAttributes`.

**Comment by shysaur** [comment]
Also, I don't like much having all this mess of forwarded properties on MGSFragaria... Most of them are redundant anyway since we already expose the textView.

**Comment by balthisar** [comment]
From the implementation standpoint accessing the properties directly is just fine, and exposing the syntaxColouring would fit the bill nicely.

It's a major API change, but I can live with that, and if people want a _better_ Fragaria they should have very little difficulty in adjusting.

On the other hand it reveals something about the implementation details of Fragaria by forcing developers to understand the properties of the individual components. For the standard textView stuff, no problem. The ruler view and the syntaxColouring are a bit deeper down.

Another way is to develop a protocol and add the top-level properties as a category, or add a wrapper class -- MGSFragariaView is nearly a wrapper class, but I'd thought to abandon all of the properties and access its Fragaria instance directly.

I'm not picky about the final solution. It just depends on what you want exposed publicly.

**Comment by shysaur** [comment]
Obviously I don't want to expose everything. Things that, in my opinion, shouldn't be exposed are MGSSyntaxErrorController and MGSExtraInterfaceController, because they are strictly are implementation details (one could theoretically merge one into MGSFragaria and the other into SMLTextView without too much hassle, like with NSTypesetter and its internal hyphenation class).

Instead, I see some advantages in exposing the gutter view, SMLSyntaxColouring and MGSSyntaxDefinition. A developer could subclass the gutter view to customize how the gutter is drawn or to add custom application-specific stuff in it. Subclassing SMLSyntaxColouring would allow integrating another syntax coloring engine in Fragaria, maybe one for a language which Fragaria's current highlighter can't support well. Subclassing MGSSyntaxDefinition allows applications to load custom syntax definition plists from anywhere, not just the predefined locations.

That these changes also make KVO more feasible is yet another good reason to make them. Obviously I won't kill all the convenience methods in MGSFragaria, just the more insane ones (like all those NSColors forwarded from the syntax highlighter!)

**Comment by balthisar** [comment]
I'll close this in favor of #54. I didn't do anything with property elimination; simply gave RO access to the syntaxColouring instance.

**Pull request closed without merging**
